config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :calendars
  resources :trainings do
    resources :comments, only: :create
  end
  resources :games do
    resources :game_comments, only: :create
  end
  
  root to: "calendars#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :user
  has_many :trainings
  has_many :games

  def start_time
    date_and_time
  end

  def end_time
    meetingfinishtime
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :training
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :calendar, optional: true
  has_many :game_comments 

  validates :opponent, presence: true
  validates :date, presence: true
end

app/models/game_comment.rb
class GameComment < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :plan, presence: true
  validates :date, presence: true
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :user
  belongs_to :calendar, optional: true
  has_many :comments

  validates :training_menu, presence: true
  validates :date, presence: true
  validates :purpose, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trainings
  has_one :calendar
  has_many :comments
  has_many :game_comments

  validates :name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :move_to_index

  def index
    @trainings = Training.all
    @games = Game.all
    @training = Training.find_by(user_id: params[:user_id])
    @game = Game.find_by(user_id: params[:user_id])
  end

  private

  def training_params
    params.permit(:date, :training_menu, :purpose, :introspection).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    coment = Comment.create(comment_params)
    redirect_to request.referer
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, training_id: params[:training_id])
  end
end

app/controllers/game_comments_controller.rb
class GameCommentsController < ApplicationController
  def create
    game_coment = GameComment.create(game_comment_params)
    redirect_to request.referer
  end

  private

  def game_comment_params
    params.require(:game_comment).permit(:text).merge(user_id: current_user.id, game_id: params[:game_id])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :game_comment_set, only: [:edit, :show]

  def new
    @game = Game.new
  end

  def create
    @game = Game.create(game_params)
    if @game.save
      redirect_to '/'
    else
      render :new
    end
  end

  def update
    @game = Game.find(params[:id])
    if  @game.update(update_game_params)
      redirect_to "/"
    else
      render :new
    end
  end

  def destroy
    game = Game.find(params[:id])
    if game.user_id == current_user.id
      game.destroy
      redirect_to '/'
    end
  end

  private

  def game_params
    params.require(:game).permit(:date, :opponent, :result, :good_point, :game_introspection).merge(user_id: current_user.id)
  end

  def update_game_params
    params.require(:game).permit(:date, :opponent, :result, :good_point, :game_introspection).merge(user_id: current_user.id)
  end

  def game_comment_set
    @game = Game.find(params[:id])
    @game_comment = GameComment.new
    @game_comments = @game.game_comments.includes(:user)
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :comment_set, only: [:edit, :show]

  def new
    @training = Training.new
  end

  def create
    @training = Training.create(training_params)
    if @training.save
      redirect_to '/'
    else
      render :new
    end
  end

  def update
    @training = Training.find(params[:id])
    if @training.update(update_training_params)
      redirect_to "/"
    else
      render :new
    end
    
  end

  def destroy
    training = Training.find(params[:id])
    if training.user_id == current_user.id
      training.destroy
      redirect_to '/'
    end
  end

  private

  def training_params
    params.require(:training).permit(:date, :training_menu, :purpose, :introspection).merge(user_id: current_user.id)
  end

  def update_training_params
    params.require(:training).permit(:date, :training_menu, :purpose, :introspection).merge(user_id: current_user.id)
  end

  def comment_set
    @training = Training.find(params[:id])
    @comment = Comment.new
    @comments = @training.comments.includes(:user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/game_comments_helper.rb
module GameCommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendars/index.html.erb
<%= month_calendar calendars: @trainings do |date, calendar| %>
  <%= date %>
    <% @trainings.each do |event| %>
      <% if event.date == date %>
        <% if current_user.id == event.user_id %>
         <div class="training_user_name">
           <%= link_to event.user.name, edit_training_path(event), class: "text_name" %><br>
         </div>
        <% else %>
         <div class="training_user_name">
           <%=  link_to event.user.name, "/trainings/#{event.id}", class: "text_name" %><br>
         </div>
        <% end %>
      <% end %>
    <% end %>
     
     <% @games.each do |game| %>
      <% if game.date == date%>
        <% if current_user.id == game.user_id %>
          <div class="game_user_name">
            <%= link_to game.user.name, edit_game_path(game), class: "text_name"%><br>
          </div>
        <% else %>
          <div class="game_user_name">
            <%=  link_to game.user.name, "/games/#{game.id}", class:"text_name" %><br>
          </div>
        <% end %>
      <% end %>
    <% end %>
<% end %>

app/views/calendars/new.html.erb
<h1>カテゴリー選択</h1>

<div class="register">
<%= link_to("練習", new_training_path, { method: :get, class: "btn-register1"}) %>
<%= link_to("試合", new_game_path, { method: :get, class: "btn-register2"}) %>
</div>

app/views/games/edit.html.erb
<h1>試合内容</h1>
 <div class="parent">
   <%= form_with(model: @game,id: 'new_training', class: 'new_training', local: true) do |f| %>
    <%= render 'share/error_messages', model: f.object %>
      <div class="field">
        <%= f.label :日付を選択, class: 'date_lavel' %><br>
        <%= f.date_field :date, class: 'select_date' %> 
      </div>

      <div class="field">
        <%= f.label :"対戦相手" %> <br>
        <%= f.text_area :opponent, autofocus: true, class: 'opponent' %>
      </div>

      <div class="field">
        <%= f.label :"結果" %><br>
        <%= f.text_area :result, autofocus: true, class: 'result' %>
      </div>

      <div class="field">
        <%= f.label :"良かった点" %><br>
        <%= f.text_area :good_point, autofocus: true, class: 'good_point' %>
      </div>

      <div class="field">
        <%= f.label :"反省点" %><br>
        <%= f.text_area :game_introspection, autofocus: true, class: 'game_introspection' %>
      </div>

      <div class="register_actions">
        <div class="actions">
          <%= f.submit "変更", class: 'change_btn' %>
        
           <div class="change_field">
             <%= link_to '削除', game_path, method: :delete, class: 'delete_btn' %>
           </div>
        </div>
      </div>
    <% end %>


      <div class="comment_contents">
        <div class="container">
         <strong>コメントをしてください<strong>
          <% if current_user %>
           <%= form_with(model: [@game, @game_comment], local: true) do |f| %>
             <%= f.text_area :text, placeholder: "コメントする", rows: "2", class: 'comment_area' %><br>
            <div class="submit_btn">
             <%= f.submit "送信", class: 'send_btn' %>
            </div>
           <% end %>
          <% end %>
          <div class="comments">
            <div class=comment_title>
              <h4>＜コメント一覧＞</h4>
            </div>
              <% if @game_comments %>
                <% @game_comments.each do |comment| %>
                 <p>
                  <strong><%= comment.user.name %>：</strong>
                    <%= comment.text %>
                 </p>
                <% end %>
              <% end %>
          </div>
        </div>
      </div>
 </div>

app/views/games/new.html.erb
<h1>試合内容</h1>
 <div class="parent">
   <%= form_with model: @game, id: 'new_game', class: 'new_game', local: true do |f| %>
    <%= render 'share/error_messages', model: f.object %>
      <div class="field">
        <%= f.label :日付を選択, class: 'date_lavel' %><br>
        <%= f.date_field :date, class: 'select_date' %> 
      </div>

      <div class="field">
        <%= f.label :"対戦相手" %> <br>
        <%= f.text_area :opponent, autofocus: true, class: 'opponent' %>
      </div>

      <div class="field">
        <%= f.label :"結果" %><br>
        <%= f.text_area :result, autofocus: true, class: 'result' %>
      </div>

      <div class="field">
        <%= f.label :"良かった点" %><br>
        <%= f.text_area :good_point, autofocus: true, class: 'good_point' %>
      </div>

      <div class="field">
        <%= f.label :"反省点" %><br>
        <%= f.text_area :game_introspection, autofocus: true, class: 'game_introspection' %>
      </div>

      <div class="register_actions">
        <div class="actions">
          <%= f.submit "登録",class: "register_btn" %>
        </div>
      </div>
   <% end %>
  </div>

app/views/games/show.html.erb
<h1>試合内容</h1>
  <div class="all_game">
    <div class="list">

      <label for="label">日付</label><br>
        <div class="label">
          <%= @game.date %><br>
        </div>

      <label for="label">対戦相手</label><br>
        <div class="label">
          <%= @game.opponent%><br>
        </div>

      <label for="label">結果</label><br>
        <div class="label">
          <%= @game.result %><br>
        </div>

      <label for="label">良かった点</label><br>
        <div class="label">
          <%= @game.good_point %><br>
        </div>

      <label for="label">反省</label><br>
        <div class="label">
          <%= @game.game_introspection %><br>
        </div>
    </div>
    
    <div class="comment_contents">
      <div class="container">
        <% if current_user %>
         <strong>コメントをしてください<strong>
          <%= form_with(model: [@game, @game_comment], local: true) do |f| %>
            <%= f.text_area :text, placeholder: "コメントする", rows: "2",class: 'comment_area' %><br>
             <div class="submit_btn">
               <%= f.submit "送信", class: 'send_btn' %>
             </div>
          <% end %>
        <% end %>
          <div class="comments">
            <div class=comment_title>
              <h4>＜コメント一覧＞</h4>
            </div>
              <% if @game_comments %>
                <% @game_comments.each do |comment| %>
                 <p>
                   <strong><%= comment.user.name %>：</strong>
                  <%= comment.text %>
                 </p>
                <% end %>
              <% end %>
          </div>
      </div>
    </div>
  </div>

app/views/games/update.html.erb
<div class="success">
  <div class="update">
    <h3>更新が完了しました。</h3>
  </div>
  <div class=root_link>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/trainings/edit.html.erb
<h1>練習内容</h1>
 <div class="parent">
   <%= form_with(model: @training,id: 'new_training', class: 'new_training', local: true) do |f| %>
     <div class="field">
       <%= f.label :日付を選択, class: 'date_lavel' %><br>
       <%= f.date_field :date, class: 'select_date' %> 
      </div>

      <div class="field">
        <%= f.label :"練習メニュー" %> <br>
        <%= f.text_area :training_menu, autofocus: true, class: 'training_menu' %>
      </div>

      <div class="field">
        <%= f.label :"目的" %><br>
        <%= f.text_area :purpose, autofocus: true, class: 'purpose' %>
      </div>

      <div class="field">
        <%= f.label :"反省" %><br>
        <%= f.text_area :introspection, autofocus: true, class: 'introspection' %>
      </div>

      <div class="field">
        <div class="actions">
          <%= f.submit "変更", class: 'change_btn' %>
       

          <div class="change_field">
            <%= link_to '削除', training_path, method: :delete, class: 'delete_btn' %>
          </div>
        </div>
      </div>
   <% end %>

      <div class="comment_contents">
        <div class="container">
         <strong>コメントをしてください<strong>
          <% if current_user %>
            <%= form_with(model: [@training, @comment], local: true) do |f| %>
              <%= f.text_area :text, placeholder: "コメントする", rows: "2", class: 'comment_area' %><br>
                <div class="submit_btn">
                  <%= f.submit "送信", class: 'send_btn' %>
                </div>
            <% end %>
          <% end %>
           <div class="comments">
              <div class=comment_title>
               <h4>＜コメント一覧＞</h4>
              </div>
                <% if @comments %>
                   <% @comments.each do |comment| %>
                    <p>
                     <strong><%= comment.user.name %>：</strong>
                     <%= comment.text %>
                    </p>
                   <% end %>
                <% end %>
           </div>
        </div>
      </div>
 </div>
   

app/views/trainings/new.html.erb
<h1>練習内容</h1>
 <div class="parent">
   <%= form_with model: @training, id: 'new_training', class: 'new_training',local: true do |f| %>
    <%= render 'share/error_messages', model: f.object %>
      <div class="field">
        <%= f.label :日付を選択, class: 'date_lavel' %><br>
        <%= f.date_field :date, class: 'select_date' %> 
      </div>

      <div class="field">
        <%= f.label :"練習メニュー" %> <br>
        <%= f.text_area :training_menu, autofocus: true, class: "training_menu" %>
      </div>

      <div class="field">
        <%= f.label :"目的" %><br>
        <%= f.text_area :purpose, autofocus: true, class: "purpose" %>
      </div>

      <div class="field">
        <%= f.label :"反省" %><br>
        <%= f.text_area :introspection, autofocus: true, class: "introspection" %>
      </div>

        <div class="register_actions">
          <div class="actions">
            <%= f.submit "登録", class: "register_btn" %>
          </div>
        </div>
   <% end %>
 </div>

app/views/trainings/show.html.erb
<h1>練習内容</h1>
  <div class="all_training">
    <div class="list">

      <label for="label">日付</label><br>
        <div class="label">
          <%= @training.date %><br>
        </div>

      <label for="label">練習メニュー</label><br>
        <div class="label">
          <%= @training.training_menu %>
        </div>

      <label for="label">目的</label><br>
        <div class="label">
          <%= @training.purpose %><br>
        </div>
        
      <label for="label">反省</label><br>
        <div class="label">
          <%= @training.introspection%><br>
        </div>
    </div>
    
    <div class="comment_contents">
      <div class="container">
        <% if current_user %>
         <strong>コメントをしてください<strong>
          <%= form_with(model: [@training, @comment], local: true) do |f| %>
            <%= f.text_area :text, placeholder: "コメントする", rows: "2", class: 'comment_area' %><br>
             <div class="submit_btn">
               <%= f.submit "送信", class: 'send_btn' %>
             </div>
          <% end %>
        <% end %>
          <div class="comments">
            <div class=comment_title>
              <h4>＜コメント一覧＞</h4>
            </div>
              <% if @comments %>
                <% @comments.each do |comment| %>
                 <p>
                   <strong><%= comment.user.name %>：</strong>
                   <%= comment.text %>
                 </p>
                <% end %>
              <% end %>
          </div>
      </div>
    </div>
  </div>

app/views/trainings/training.html.erb
<div class="success">
  <div class="update">
    <h3>更新が完了しました。</h3>
  </div>
  <div class=root_link>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/trainings/update.html.erb
<div class="success">
  <div class="update">
    <h3>更新が完了しました。</h3>
  </div>
  <div class=root_link>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "ページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>